<?php
return array(
	'btn_bgcolor' 		=> csoptionepis('hnbtn_player_bgcolor') ?? '#0b0f15',
	'btn_textcolor' 	=> csoptionepis('hnbtn_player_textcolor') ?? '#fff',
	'btn_hover' 		=> csoptionepis('hnbtn_player_hover') ?? '#0369A1',
	'btn_radius' 		=> csoptionepis('hnbtn_player_radius') ? csoptionepis('hnbtn_player_radius').'px' : '4px',
	'backupbg' 			=> csoptionepis('hnbtn_backupbg') ?? '#0b0f15',
	'backuptext' 		=> csoptionepis('hnbtn_backuptext') ?? '#fff',
	'backuphover' 		=> csoptionepis('hnbtn_backuphover') ?? '#e87d7f',
	'backupbgactive' 	=> csoptionepis('hnbtn_backupbgactive') ?? '#f2a900',
	'backuptextactive' 	=> csoptionepis('hnbtn_backuptextactive') ?? '#702526',
	'bordersv' 			=> csoptionepis('hnbtn_bordersv') ? csoptionepis('hnbtn_bordersv').'px' : '0px',
	'episbgcolor' 		=> csoptionepis('hnepis_bgcolor') ?? '#344156',
	'episbghover' 		=> csoptionepis('hnepis_bghover') ?? '#000',
	'episbglist' 		=> csoptionepis('hnepis_bglist') ?? '#0b0f15',
	'epistextsv' 		=> csoptionepis('hnepis_textsv') ?? '#ea9b06',
	'commentsbg' 		=> csoptionepis('comments_bgcolor') ?? '#ea9b06',
	'quicklybg' 		=> csoptionepis('quickly_bgcolor') ?? '#1a1a1a',
	'quicklytext' 		=> csoptionepis('quickly_textcolor') ?? '#fff',
	'quicklyborder' 	=> csoptionepis('quickly_bordercolor') ?? '#1a1a1a',
	'fivebg' 			=> csoptionepis('five_bgcolor') ?? '#282828',
	'fivetext' 			=> csoptionepis('five_textcolor') ?? '#fdfdfd',
	'fivebutton' 		=> csoptionepis('five_buttonbgcolor') ?? '#3a3a3a',
	'hnfamily' 			=> csoptionepis('hn_fonts')['font-family'] ?? 'hncore',
);
