<?php

return array(
	'publish'                                       	=> __('Publish', 'hnmgepis'),
	'label'                                         	=> __('Label', 'hnmgepis'),
	'loading'                                       	=> __('Loading...', 'hnmgepis'),
	'choose_type'                                   	=> __('Choose Type', 'hnmgepis'),
	'sub_has_update'                                	=> __('Subtitle has been updated!', 'hnmgepis'),
	'url'                                           	=> __('URL', 'hnmgepis'),
	'upload_file'                                   	=> __('Upload File', 'hnmgepis'),
	'default'                                       	=> __('Default', 'hnmgepis'),
	'upload'                                        	=> __('Upload', 'hnmgepis'),
	'please_server_name'                            	=> __('Please enter server name', 'hnmgepis'),
	'please_episode_list'                           	=> __('Please enter the episode list in the form!', 'hnmgepis'),
	'please_wait'                                   	=> __('Please wait...', 'hnmgepis'),
	'import_successfuly'                            	=> __('Import successfully!', 'hnmgepis'),
	'error'                                         	=> __('Error!', 'hnmgepis'),
	'saving'                                        	=> __('Saving...', 'hnmgepis'),
	'save'                                          	=> __('Save', 'hnmgepis'),
	'updating'                                      	=> __('Updating...', 'hnmgepis'),
	'done'                                          	=> __('Done!', 'hnmgepis'),
	'server_name'                                   	=> __('Server Name', 'hnmgepis'),
	'Name'                                          	=> __('Name', 'hnmgepis'),
	'Type'                                          	=> __('Type', 'hnmgepis'),
	'Action'                                        	=> __('Action', 'hnmgepis'),
	'Link'                                          	=> __('Link', 'hnmgepis'),
	'Alternative_Link'                              	=> __('Alternative Link', 'hnmgepis'),
	'successfully'                                  	=> __('Successfully', 'hnmgepis'),
	'update_episodes'                               	=> __('Update Episodes', 'hnmgepis'),
	'import_episode'                                	=> __('Import Episode', 'hnmgepis'),
	'update_post_info'                              	=> __('Update Post Info', 'hnmgepis'),
	'backup_successful'                             	=> __('Backup link server update successful', 'hnmgepis'),
	'please_form_notice'                            	=> __('Please enter the episode list in the form!', 'hnmgepis'),
	'please_link_list'                              	=> __('Please enter link list!', 'hnmgepis'),
	'notice_epi_to_import'                           	=>__('Please select the episode to import!', 'hnmgepis'),
	'are_delete_server'                             	=> __('Are you sure you want to delete this server & all episodes?', 'hnmgepis'),
	'add_subtitles'                                 	=> __('Add subtitles', 'hnmgepis'),
	'del_tooltip_episode'                           	=> __('Delete The Current Episode', 'hnmgepis'),
	'add_backup_server'                             	=> __('Add Backup Server', 'hnmgepis'),
	'add_field'                                     	=> __('Add Field', 'hnmgepis'),
	'update_server'                                 	=> __('Update Server', 'hnmgepis'),
	'update_subtitle'                               	=> __('Update Subtitle', 'hnmgepis'),
	'click_add_newepi'                              	=> __('Click Here To Add A New Episode', 'hnmgepis'),
	'need_subtitles_epi'                            	=> wp_kses_post(__('Need to <b>Update Episodes</b> Before <b>Adding Subtitles</b>', 'hnmgepis')),
	'need_backup_epi'                               	=> wp_kses_post(__('Need to <b>Update Episodes</b> Before <b>Backup Links</b>', 'hnmgepis'))
);
